---
- name: Deploy java application
  hosts: 172.31.28.166
  become: yes
  tasks:
   - name: Download Tomcat
     get_url: url=https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.27/bin/apache-tomcat-8.0.27.tar.gz dest=/tmp

   - name: Extract archive
     unarchive: src=/tmp/apache-tomcat-8.0.27.tar.gz dest=/tmp  remote_src=yes
  
   - name: Download Application
     copy: src=/home/ubuntu/DevOpsRocks.war dest=/tmp

   - name: start apache-tomcat-8.0.27
     command:   "nohup /tmp/apache-tomcat-8.0.27/bin/startup.sh"

   - name: copy war file
     shell: cp /tmp/DevOpsRocks.war /tmp/apache-tomcat-8.0.27/webapps/

   - name: stop apache-tomcat-8.0.27
     command:  "nohup /tmp/apache-tomcat-8.0.27/bin/shutdown.sh"
   
   - name: start apache-tomcat-8.0.27
     command:  "nohup /tmp/apache-tomcat-8.0.27/bin/startup.sh"
