---
- name: Uninstalling packages with_items
  hosts: all
  tasks:
  - name: Uninstall softwares
    apt:
     name: "{{item.a}}"
     state: "{{item.b}}"
     update_cache: "{{item.c}}"
    with_items:
     - {a: apache2, b: absent, c: yes}
     - {a: firewalld, b: absent, c: yes}
     - {a: unzip, b: absent, c: yes}
...
