---
- name: Install multiple packages
  hosts: all
  tasks:
  - name: Install packages
    apt:
     name: "{{item}}"
     state: present
     update_cache: no
    with_items:
     - unzip
     - firewalld
...
