---
- name: Tomcat installation
  hosts: 172.31.28.166
  become: yes
  tasks:
  - name: Download tomcat8
    get_url:
     url: https://archive.apache.org/dist/tomcat/tomcat-8/v8.0.27/bin/apache-tomcat-8.0.27.zip
     dest: /home/ubuntu
  - name: Install unzip package
    apt:
     name: unzip
     state: present
  - name: Unarchive zip file
    unarchive:
     src: /home/ubuntu/apache-tomcat-8.0.27.zip
     dest: /home/ubuntu
     remote_src: yes
  - name: start apache-tomcat-8.0.27
    command:  "nohup /home/ubuntu/apache-tomcat-8.0.27/bin/startup.sh"
...
